In [ ]:
# How to create numpy array
import numpy as np

In [ ]:
# np.array()
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
list1=[5,6,7,8]
arr1=np.array(list1)
print(arr1)
print(type(arr1))

[5 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
#Attributes of Arrays
#dim, shape, size,dtype
print(arr1)
print(arr1.ndim)

[5 6 7 8]
1


In [ ]:
print(arr1.shape)

(4,)


In [ ]:
print(arr1.size)

4


In [ ]:
print(arr1.dtype)#int64-integer data where every data is of 8 byte

int64


In [ ]:
# Create 2-D Array
arr2=np.array([[1,2,3],[4,5,6]],dtype='float64')
print(arr2)


[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 3)
6
float64


In [ ]:
# Create 2-D Array
arr2=np.array([['a','b'],['c','d']])
print(arr2)

[['a' 'b']
 ['c' 'd']]


In [ ]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)# when we string data every element is of 4 byte
print(arr2.dtype)#unicode char

2
(2, 2)
4
<U1


In [ ]:
arr2=np.array([[1,2,3],[4,5,6]],dtype='float64')
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 3)
6
float64


In [ ]:
#basic operations on arrays
#arithmetic operations
#logical
#comparison
distance=np.array([10,12,15,17,20])
time=np.array([0.3,0.7,0.65,0.78,0.9])

In [ ]:
print(distance)
print(time)

[10 12 15 17 20]
[0.3  0.7  0.65 0.78 0.9 ]


In [ ]:
speed=distance/time
print(speed)

[33.33333333 17.14285714 23.07692308 21.79487179 22.22222222]


In [ ]:
# multiply one value with the array
distance=distance*3

In [ ]:
print(distance)

[30 36 45 51 60]


In [ ]:
#divide
distance=distance/2
print(distance)

[15.  18.  22.5 25.5 30. ]


In [ ]:
new=np.array([1,2,3,4,5])

In [ ]:
distance-new #ndarray should be of same shape

array([14. , 16. , 19.5, 21.5, 25. ])

In [ ]:
# Access array elements with the indexing
distance_covered=np.array([[2,4,6,8],[3,6,9,12]])

In [ ]:
distance_covered.ndim

2

In [ ]:
distance_covered[0]

array([2, 4, 6, 8])

In [ ]:
distance_covered[1]

array([ 3,  6,  9, 12])

In [ ]:
distance_covered[0,0]

2

In [ ]:
distance_covered[0,:] # : ALL

array([2, 4, 6, 8])

In [ ]:
distance_covered[1,:]

array([ 3,  6,  9, 12])

In [ ]:
distance_covered[:,1]

array([4, 6])

In [ ]:
print(distance_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
distance_covered[1,:]

array([ 3,  6,  9, 12])

In [ ]:
distance_covered[:,2] # 2 is the direct col number

array([6, 9])

In [ ]:
distance_covered[:,:2] # 0:2 0 is the start index , so its inclusive, 2 is the end index 2-1

array([[2, 4],
       [3, 6]])

In [ ]:
distance_covered[:,2:]

array([[ 6,  8],
       [ 9, 12]])

In [ ]:
print(distance_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
#[4,6]
#[6,9]
distance_covered[:,1:3]

array([[4, 6],
       [6, 9]])

In [ ]:
distance_covered[:,0]

array([2, 3])

In [ ]:
#Conditional selection
print(distance_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
distance_covered>5

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [ ]:
distance_covered[distance_covered>5]

array([ 6,  8,  6,  9, 12])

In [ ]:
# check which are equal to 6
distance_covered[distance_covered==6]

array([6, 6])

In [ ]:
# check which are equal to 6, size
distance_covered[distance_covered==6].size

2

In [ ]:
# print the size of elements which are greater than 6
distance_covered[distance_covered > 6].size

3

In [ ]:
#Universal functions
arr=np.array([1,3,5,6,8])

In [ ]:
#square root
print(np.sqrt(arr))

[1.         1.73205081 2.23606798 2.44948974 2.82842712]


In [ ]:
#mean 
print(np.mean(arr))

4.6


In [ ]:
# standard deviation
print(np.std(arr))

2.4166091947189146


In [ ]:
# variance
print(np.var(arr))

5.84


In [ ]:
# median
print(np.median(arr))

5.0


In [ ]:
print(np.min(arr))

1


In [ ]:
arr2=np.array([1.75,2.6,3.4])

In [ ]:
a=np.floor([arr2])

In [ ]:
a

array([[1., 2., 3.]])

In [ ]:
b=np.ceil([arr2])

In [ ]:
b

array([[2., 3., 4.]])

In [ ]:
#Shape Manipulation
print(distance_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
#ravel() in 1-D Array
distance_covered.ravel() #flattens into 1-D array

array([ 2,  4,  6,  8,  3,  6,  9, 12])

In [ ]:
#reshape method
distance_covered.shape

(2, 4)

In [ ]:
distance_covered.reshape(2,2,2)

array([[[ 2,  4],
        [ 6,  8]],

       [[ 3,  6],
        [ 9, 12]]])

In [ ]:
distance_covered.reshape(8,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [12]])

In [ ]:
#resize the array
distance_covered.reshape(2,4)

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [ ]:
distance_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [ ]:
# with arange method
# an array of 10 elements
new=np.arange(10)

In [ ]:
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new.ndim

1

In [ ]:
new=np.arange(5,20)
new

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# create array & reshape array
new=np.arange(12).reshape(4,3)
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# create 10 elements array reshape it into 5*2

In [ ]:
# Splitting array
distance_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [ ]:
#splitting col wise
#hsplit
np.hsplit(distance_covered,2)

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [ ]:
arr2=np.arange(12).reshape(6,2)
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vsplit(arr2,3)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]])]

In [ ]:
# Different kind of Matrix
#generate array of 0s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# create matrix with all ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2),dtype="int")

array([[1, 1],
       [1, 1]])

In [ ]:
#linspace -returns evenly spaced numbers
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [ ]:
# identical matrix
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#Random Numbers
# rand function
np.random.rand(5) # [0,1]

array([0.17430212, 0.00699777, 0.81797069, 0.43161997, 0.88633947])

In [ ]:
np.random.rand(3,2)

array([[0.25977864, 0.50663465],
       [0.98595494, 0.48463912],
       [0.54042477, 0.6822341 ]])

In [ ]:
# Generate random integer number
np.random.randint(5,20) #randint function generate a single random number when we pass a range

10

In [ ]:
np.random.randint(5,20,(2,2))

array([[ 6,  5],
       [12, 16]])

In [ ]:
#randn function- generate numbers standard normal distribution
a=np.random.randn(5) 

In [ ]:
np.mean(a)

0.7564951213974221

In [ ]:
np.std(a)

0.2189202558198003